import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const API='http://localhost:8000/api';

function App(){
 const [people,setPeople]=useState([]),[selected,setSelected]=useState(null),[date,setDate]=useState(null),[rankings,setRankings]=useState(null),[allRanks,setAllRanks]=useState(null),[tab,setTab]=useState('people'),[dateA,setDateA]=useState(''),[dateB,setDateB]=useState(''),[dateList,setDateList]=useState([]);
 const [li,setLi]=useState(''),[ig,setIg]=useState(''),[busy,setBusy]=useState(false),[stage,setStage]=useState('');
 useEffect(()=>{fetch(API+'/people').then(r=>r.json()).then(setPeople)},[]);
 const profile=async id=>{setBusy(true);setStage('Loading public profile links…');const p=await (await fetch(API+'/people/'+id)).json();setSelected(p);setRankings(null);setTab('profile');setBusy(false)};
 const analyze=async id=>{setBusy(true);setTab('profile');setStage('Reading LinkedIn…');await new Promise(r=>setTimeout(r,450));setStage('Reading Instagram…');await new Promise(r=>setTimeout(r,450));setStage('Extracting public signals…');await new Promise(r=>setTimeout(r,450));const r=await fetch(API+'/analyze/'+id,{method:'POST'});const d=await r.json();setSelected(d.person);setStage(d.status==='complete'?'Agent ready':'Source access required');await new Promise(r=>setTimeout(r,250));setBusy(false)};
 const runDate=async(id1,id2)=>{if(!id1||!id2||id1===id2)return;setBusy(true);setStage('Agents are meeting…');const d=await (await fetch(`${API}/date/${id1}/${id2}`,{method:'POST'})).json();setDate(d);setTab('date');setBusy(false)};
 const openDatingRoom=()=>{setDateA(String(people[0]?.id||''));setDateB(String(people[1]?.id||''));setTab('dating');};
 const runDemoDates=async()=>{setBusy(true);setStage('Agents are meeting across the pool…');const d=await (await fetch(`${API}/dates/demo?limit=12`,{method:'POST'})).json();setDateList(d.dates||[]);setTab('dating');setBusy(false)};
 const runRank=async id=>{setBusy(true);setStage('Running personalized matches…');const r=await (await fetch(API+'/rankings/'+id)).json();setRankings(r);setTab('rankings');setBusy(false)};
 const runAllRanks=async()=>{setBusy(true);setStage('Running all 25 personalized rankings…');const r=await (await fetch(API+'/rankings/all',{method:'POST'})).json();setAllRanks(r);setTab('allrankings');setBusy(false)};
 const add=async e=>{e.preventDefault();setBusy(true);setStage('Creating agent…');const r=await fetch(API+'/people/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({linkedin:li,instagram:ig})});const p=await r.json();setPeople([...people,p]);setLi('');setIg('');setSelected(p);setTab('profile');setBusy(false)};
 return <div className="app"><header><div className="logo">♡ AgentMatch</div><nav><button onClick={()=>setTab('people')}>People</button><button onClick={openDatingRoom}>Dating room</button><button onClick={()=>setTab('rankings')}>Rankings</button><button onClick={runAllRanks}>Run all matches</button></nav></header>
 <main><section className="hero"><div><span className="pill">✦ AGENTIC DATING · 25 PEOPLE</span><h1>Let their agents<br/><em>meet first.</em></h1><p>Two public sources become a transparent agent profile. Agents then meet, converse and rank compatibility.</p><div className="flow"><span>◉ LinkedIn</span><b>+</b><span>◎ Instagram</span><b>→</b><span>✦ Agent</span><b>→</b><span>♡ Date</span><b>→</b><span>↗ Ranking</span></div></div><form onSubmit={add} className="import"><h3>Create an agent</h3><input required placeholder="LinkedIn public URL" value={li} onChange={e=>setLi(e.target.value)}/><input required placeholder="Instagram public URL" value={ig} onChange={e=>setIg(e.target.value)}/><button className="primary">Create agent →</button><small>URLs are validated. Existing demo profiles use normalized public-source data; arbitrary LinkedIn profiles require an authorized integration or supplied profile data.</small></form></section>
 {busy&&<div className="progress"><span className="dot"/> {stage}</div>}
 <div className="tabs"><button className={tab==='people'?'active':''} onClick={()=>setTab('people')}>People · {people.length}</button><button className={tab==='profile'?'active':''} onClick={()=>selected&&setTab('profile')}>Profile analysis</button><button className={tab==='date'?'active':''} onClick={()=>date&&setTab('date')}>Agent date</button><button className={tab==='dating'?'active':''} onClick={openDatingRoom}>Dating room</button><button className={tab==='rankings'?'active':''} onClick={()=>setTab('rankings')}>Rankings</button><button className={tab==='allrankings'?'active':''} onClick={runAllRanks}>All 25 rankings</button></div>
 {tab==='people'&&<div className="grid">{people.map(p=><article className="card" key={p.id}><div className="avatar">{p.name[0]}</div><h3>{p.name}</h3><p>{p.headline}</p><div className="chips">{(p.interests||[]).slice(0,3).map(x=><span key={x}>{x}</span>)}</div><div className="actions"><button onClick={()=>analyze(p.id)}>Analyze</button><button onClick={()=>runRank(p.id)}>Rankings</button></div></article>)}</div>}
 {tab==='profile'&&selected&&<Profile p={selected} people={people} onAnalyze={analyze} onDate={runDate} onRank={runRank}/>} 
 {tab==='date'&&date&&<DateView d={date}/>}
 {tab==='dating'&&<DatingRoom people={people} a={dateA} b={dateB} setA={setDateA} setB={setDateB} onDate={()=>runDate(Number(dateA),Number(dateB))} onDemo={runDemoDates} dates={dateList}/>} 
 {tab==='rankings'&&rankings&&<Rankings r={rankings}/>}
 {tab==='allrankings'&&<AllRankings data={allRanks} onOpen={r=>{setRankings(r);setTab('rankings')}} onRun={runAllRanks}/>} 
 {tab==='rankings'&&!rankings&&<div className="choose"><h2>Choose an agent</h2><p>Analyze a profile, then run its personalized ranking.</p></div>}
 </main></div>
}
function Profile({p,people,onAnalyze,onDate,onRank}){let other=people.find(x=>x.id!==p.id);return <div className="profile"><div className="profileHead"><div className="avatar big">{p.name[0]}</div><div><span className="pill">AGENT PROFILE</span><h2>{p.name}</h2><p>{p.headline}</p><small>{p.location}</small></div></div><div className="sources"><a href={p.linkedin} target="_blank">LinkedIn ↗</a><a href={p.instagram} target="_blank">Instagram ↗</a><span>Exactly two sources</span></div><div className="cols"><Box title="Needs" items={p.needs||[]}/><Box title="Hobbies" items={p.hobbies||[]}/><Box title="Interests" items={p.interests||[]}/></div><div className="evidence"><div className="evidenceHead"><b>How the agent analyzed the person</b><button onClick={()=>onAnalyze(p.id)}>↻ Re-run analysis</button></div><div className="statusLine">Source status: <b>{p.analysis_status==='complete'?'Analyzed from bundled normalized public-source record':'URLs validated; authorized source content still required'}</b></div><div className="evidenceGrid"><div><strong>LinkedIn signals</strong>{(p.source_analysis?.linkedin||['Public professional context normalized from the supplied source.']).map(x=><p key={x}>✓ {x}</p>)}</div><div><strong>Instagram signals</strong>{(p.source_analysis?.instagram||['Public-content signals normalized from the supplied source.']).map(x=><p key={x}>✓ {x}</p>)}</div></div></div><div className="cta"><button className="primary" onClick={()=>onDate(p.id,other.id)}>▶ Watch agents date</button><button onClick={()=>onRank(p.id)}>View my rankings →</button></div></div>}
function Box({title,items}){return <div className="box"><h3>{title}</h3>{items.map(x=><div className="item" key={x}>{x}</div>)}</div>}
function DateView({d}){return <div className="date"><div className="dateTop"><span>LIVE AGENT DATE</span><strong>{d.score}% compatibility</strong></div><div className="dateNames"><div><div className="avatar">{d.a.name[0]}</div>{d.a.name}</div><div className="heart">♡</div><div><div className="avatar">{d.b.name[0]}</div>{d.b.name}</div></div><div className="chat">{d.conversation.map((m,i)=><div key={i} className={'bubble '+(m.speaker===d.a.name?'left':'right')}><b>{m.speaker}</b><p>{m.message}</p></div>)}</div><div className="match"><b>Why the agents connected</b><p>{d.reason}</p>{d.shared_interests.length>0&&<div className="chips">{d.shared_interests.map(x=><span key={x}>✓ {x}</span>)}</div>}</div></div>}
function DatingRoom({people,a,b,setA,setB,onDate,onDemo,dates}){return <div className="datingRoom"><div className="roomHead"><span className="pill">AGENT DATING LAB</span><h2>Let two agents meet.</h2><p>Pick any two profiles and watch their agents explore shared signals, differences and conversational fit.</p></div><div className="datePicker"><select value={a} onChange={e=>setA(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="heart">♡</div><select value={b} onChange={e=>setB(e.target.value)}>{people.filter(p=>String(p.id)!==String(a)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="primary" onClick={onDate}>▶ Start date</button></div><button className="demoButton" onClick={onDemo}>Run a 12-date demo set →</button>{dates.length>0&&<div className="dateGrid">{dates.map((d,i)=><button key={i} onClick={()=>{setA(String(d.a.id));setB(String(d.b.id));}} className="dateCard"><span>{d.a.name} × {d.b.name}</span><strong>{d.score}%</strong><small>{d.shared_interests.join(' · ')||'General interests'}</small></button>)}</div>}</div>}
function AllRankings({data,onOpen,onRun}){return <div className="allRankings"><div className="rankTitle"><div><span className="pill">FULL MATCH RUN</span><h2>25 agents. 25 personalized rankings.</h2><p>Every agent gets its own ordering of the other profiles.</p></div><button className="primary" onClick={onRun}>↻ Re-run all</button></div>{!data?<div className="choose"><h2>Ready to run</h2><p>Generate all personalized rankings in one click.</p><button className="primary" onClick={onRun}>Run all 25 rankings →</button></div>:<div className="overviewGrid">{data.results.map(r=><button className="overviewCard" key={r.person.id} onClick={()=>onOpen(r)}><div className="avatar">{r.person.name[0]}</div><div><b>{r.person.name}</b><small>Top match</small><strong>{r.rankings[0]?.person.name||'—'} · {r.rankings[0]?.score||0}%</strong></div><span>→</span></button>)}</div>}</div>}
function Rankings({r}){return <div className="rank"><div className="rankTitle"><div><span className="pill">PERSONALIZED</span><h2>{r.person.name}'s rankings</h2><p>Every ranking is calculated from this agent's profile signals.</p></div></div>{r.rankings.map(x=><div className="rankRow" key={x.person.id}><div className="rankNum">{x.rank}</div><div className="avatar">{x.person.name[0]}</div><div className="rankInfo"><b>{x.person.name}</b><small>{x.person.headline}</small><span>{x.reason}</span></div><strong>{x.score}</strong></div>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
